Added accessibility example to widget
agents-lp/agents-lp.github.io pull request #12
Opened 2021-02-15 14:54 UTC by SerGYashchuk

Added accessibility example

2021-02-15 21:13 UTC, meirotstein requested changes

2021-02-15 21:13 UTC, meirotstein commented on quick-replies-widget/lib/data.js
> +            title: "accessibility",
Please provide more descriptive name, something like: 'buttons with accessibility attributes'

2021-02-16 10:30 UTC, SerGYashchuk commented on quick-replies-widget/lib/data.js
> +            title: "accessibility",
@meirotstein updated, thanks!

2021-02-17 15:21 UTC, kelvingraddick approved these changes

2021-02-18 08:47 UTC, kelvingraddick commented
@meirotstein can you merge this if you think it's ready? I don't have access here unfortunately.

2021-02-18 10:34 UTC, merged